// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0U3O_M6ZDpGxN-SMor4mmJc0URLYZmY',
    appId: '1:751343341811:web:5b43431cdbe97d47f42786',
    messagingSenderId: '751343341811',
    projectId: 'reserve-app-15815',
    authDomain: 'reserve-app-15815.firebaseapp.com',
    databaseURL: 'https://reserve-app-15815-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-app-15815.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKvULt_8oTOCorNmePgl2M96m65nDsVQ',
    appId: '1:751343341811:android:34fda6c6c8ba6584f42786',
    messagingSenderId: '751343341811',
    projectId: 'reserve-app-15815',
    databaseURL: 'https://reserve-app-15815-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-app-15815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTypU6v21R44NwDV2nroA20qBLFSG_9c',
    appId: '1:751343341811:ios:d7794aa9e7f0e180f42786',
    messagingSenderId: '751343341811',
    projectId: 'reserve-app-15815',
    databaseURL: 'https://reserve-app-15815-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-app-15815.firebasestorage.app',
    iosClientId: '751343341811-bru3gt579tj8rg73fohqu7cscft5ns7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.reserveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRTypU6v21R44NwDV2nroA20qBLFSG_9c',
    appId: '1:751343341811:ios:d7794aa9e7f0e180f42786',
    messagingSenderId: '751343341811',
    projectId: 'reserve-app-15815',
    databaseURL: 'https://reserve-app-15815-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-app-15815.firebasestorage.app',
    iosClientId: '751343341811-bru3gt579tj8rg73fohqu7cscft5ns7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.reserveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE0U3O_M6ZDpGxN-SMor4mmJc0URLYZmY',
    appId: '1:751343341811:web:a86374fe17cbb1ecf42786',
    messagingSenderId: '751343341811',
    projectId: 'reserve-app-15815',
    authDomain: 'reserve-app-15815.firebaseapp.com',
    databaseURL: 'https://reserve-app-15815-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-app-15815.firebasestorage.app',
  );
}
